<a href="https://colab.research.google.com/github/ClaraCastro118/GIT-PLAYGROUND-INFINITY-/blob/main/aula04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

coleções
estruturas q permitem armazenar mais dados multualmente

# Coleções

São estruturas de dados que permite armazenar mais de um valor.


Usar tuplas para montar estruturas de dados heterogêneos enquanto a lista deveria ser usada para dados homogêneos, ou seja, todos seus elementos deveriam ser do mesmo tipo.

In [1]:
#tuplas não pode mudar valor

garagem = ("honda civic", "toyota corola", "ford focus", 235 , True)


In [2]:
garagem

('honda civic', 'toyota corola', 'ford focus', 235, True)

In [3]:
garagem[0]

'honda civic'

In [4]:
garagem [2]

'ford focus'

In [5]:
garagem.index ("toyota corola")

1

In [6]:
for elemento in garagem :
  print(elemento)

honda civic
toyota corola
ford focus
235
True


Listas

In [13]:
l1 = ["golf","cruze","elantra"]

In [8]:
l2 = ["fiat 500", "tesla model x"]

In [14]:
l3 = l1 + l2

In [15]:
print(l3)

['golf', 'cruze', 'elantra', 'fiat 500', 'tesla model x']


In [16]:
l2_2 = l2*2

In [17]:
l2_2

['fiat 500', 'tesla model x', 'fiat 500', 'tesla model x']

In [18]:
l1[2]

'elantra'

In [19]:
l1

['golf', 'cruze', 'elantra']

In [20]:
l1[0:2]

['golf', 'cruze']

In [21]:
l1[0:3]

['golf', 'cruze', 'elantra']

In [22]:
#adicionando um novo elemento a lista
l1.append('young pro')

print(l1)

['golf', 'cruze', 'elantra', 'young pro']


In [23]:
l1.remove('young pro')

print(l1)

['golf', 'cruze', 'elantra']


In [24]:
del(l1)


In [25]:
print(l1)

NameError: name 'l1' is not defined

In [30]:
for item in l2_2:
  print(item)

fiat 500
tesla model x
fiat 500
tesla model x


In [66]:
#dicionarios

["civic","civic","civic", "corola","corola","x1","x1","x1","x1"]

['civic', 'civic', 'civic', 'corola', 'corola', 'x1', 'x1', 'x1', 'x1']

In [67]:
garagem3 ={"ford mustang":3,"chevrolet camaro":5 ,"dodge charge":2}

In [68]:
garagem3 ["chevrolet camaro"]

5

In [70]:
garagem3["BMW X1"] = 11

In [71]:
print(garagem3)

{'ford mustang': 3, 'chevrolet camaro': 5, 'dodge charge': 2, 'BMW X1': 11}


In [72]:
del(garagem3)["BMW X1"]
print(garagem3)

{'ford mustang': 3, 'chevrolet camaro': 5, 'dodge charge': 2}


In [73]:
garagem3.items()

dict_items([('ford mustang', 3), ('chevrolet camaro', 5), ('dodge charge', 2)])

In [75]:
garagem3.keys()

dict_keys(['ford mustang', 'chevrolet camaro', 'dodge charge'])

In [77]:
garagem3.values()

dict_values([3, 5, 2])

In [78]:
garagem4 = {"porche 911":4,"lamborghini huracan":6}
print(garagem4)

{'porche 911': 4, 'lamborghini huracan': 6}


In [79]:
#unindo dois dicionarios

garagem3.update(garagem4)
print(garagem3)

{'ford mustang': 3, 'chevrolet camaro': 5, 'dodge charge': 2, 'porche 911': 4, 'lamborghini huracan': 6}


In [80]:
garagem3.items()

dict_items([('ford mustang', 3), ('chevrolet camaro', 5), ('dodge charge', 2), ('porche 911', 4), ('lamborghini huracan', 6)])

In [83]:
#percorrendo um dicionario

for exemplar , num_exemplar in garagem3.items():
  print(f"exemplar: {exemplar} , quantidade: {num_exemplar}")



exemplar: ford mustang , quantidade: 3
exemplar: chevrolet camaro , quantidade: 5
exemplar: dodge charge , quantidade: 2
exemplar: porche 911 , quantidade: 4
exemplar: lamborghini huracan , quantidade: 6


In [ ]:
#conjunto de sets

#valores sem ordem , e nao duplicados
#nao é possivel modificar itens existentes mas pode add novos itens


## Conjuntos (set)

Um conjunto é uma coleção não ordenada de valores únicos.
1. Armazena apenas itens não duplicados (únicos).
2. Suporta operações matemáticas sobre conjuntos, como união e interseção.
3. Não é possível modificar os itens existentes, mas podemos adicionar novos elementos (conjuntos são mutáveis).
4. Suporta elementos de qualquer tipo, não ordenados e não indexados.
5. Pode conter apenas objetos imutáveis, como strings, ints, floats e tuplas de objetos também imutáveis.
6. São escritos com chaves {}.

In [86]:
biomoleculas = {"proteina","acidos nucleicos","carboidratos","lipidios","acidos nucleicos","carboidratos"}

In [87]:
print(biomoleculas)

{'lipidios', 'carboidratos', 'proteina', 'acidos nucleicos'}


In [88]:
garagem

('honda civic', 'toyota corola', 'ford focus', 235, True)

In [89]:
print(set(garagem))

{True, 'toyota corola', 235, 'honda civic', 'ford focus'}


In [90]:
#criando conjuntos

c1 ={1,2,3,4,5}
c2 ={3,4,5,6,7}

In [91]:
c3 = c1.intersection(c2)
print(c3)

{3, 4, 5}


In [92]:
c1.difference(c2)

{1, 2}

In [93]:
c2.difference(c1)

{6, 7}

# Matrizes

Outro tipo de estrutura de dados que permite armazenar mais valores

Chamando a biblioteca numpy e dando um apelido a ela (np).

Biblioteca muito usada na estatística.

Arrays:
1. São estruturas de dados com tamanho fixo.
2. Geralmente usados para sequências de elementos com tamanho conhecido.
3. Mais eficientes em termos de memória e processamento.
4. Acessamos os dados por índices específicos.
5. Para trabalhar com arrays, é comum usar bibliotecas como NumPy.
5. Exemplo em Python (usando NumPy): import numpy as np; meu_array = np.array([1, 2, 3]).

In [94]:
import numpy as np

In [95]:
meu_array = np.array([1,2,3])

In [96]:
meu_array

array([1, 2, 3])

In [97]:
matriz = np.array([[2,3,1],
                  [4,5,7]])

In [98]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [99]:
matriz.shape

(2, 3)

In [100]:
matriz[0]

array([2, 3, 1])

In [101]:
matriz[1]

array([4, 5, 7])

In [102]:
matriz[0][0]

np.int64(2)

In [103]:
matriz[1][2]

np.int64(7)

In [104]:
matriz[0][2]

np.int64(1)

In [105]:

matriz.shape

(2, 3)

In [106]:
matriz.shape[0]

2

In [107]:
matriz.shape[1]

3

In [110]:
#percorrer matriz

for i in range(matriz.shape[0]):
  print(matriz[i])


[2 3 1]
[4 5 7]


In [113]:
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    print(matriz[i][j])

2
3
1
4
5
7


In [121]:
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    print(matriz[i][j],end=" ")

2 3 1 4 5 7 

In [122]:
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    print(matriz[i][j],end=" ")
  print()

2 3 1 
4 5 7 


In [125]:
# Lista: Crie uma estrutura de repetição para fazer a leitura de 5 números inteiros e os armazene dentro de uma lista.
# Após a leitura, crie outra estrutura de repetição para somar todos os valores digitados

numeros = []
for i in range(5):
  n =int(input("digite um numero: "))
  numeros.append(n)

  soma = 0
  for numero in numeros:
    soma = soma + numero
  print(f" a soma dos numeros é :", soma )


digite um numero: 7
 a soma dos numeros é : 7
digite um numero: 8
 a soma dos numeros é : 15
digite um numero: 1
 a soma dos numeros é : 16
digite um numero: 15
 a soma dos numeros é : 31
digite um numero: 33
 a soma dos numeros é : 64


In [126]:
lista=[]
for i in range(1,6):
  valor = int(input(f"digite o {i} numero: "))
  lista.append(valor)


digite o 1 numero: 1
digite o 2 numero: 5
digite o 3 numero: 8
digite o 4 numero: 3
digite o 5 numero: 7


In [127]:
lista

[1, 5, 8, 3, 7]

In [128]:
len(lista)

5

In [130]:
soma = 0
for i in range(len(lista)):
  soma = soma + lista[i]

print("soma",soma)


soma 24


In [131]:
import numpy as np

np.array(lista).sum()


np.int64(24)

In [136]:
# 2. Dicionário: Crie um dicionário para armazenar o nome e a nota de 3 alunos, fazendo a leitura dos valores por meio de uma estrutura de repetição.
# Depois, crie uma nova estrutura de repetição para somar todas as notas e retornar a média

aluno = {}
for i in range(3):
  nome = input("digite o nome do aluno: ")
  nota = float(input("digite a nota do aluno: "))
  aluno[nome] = nota

soma = 0
for nota in aluno.values():
  soma += nota

media = soma/ len(aluno)


print ("media das notas : " , media )

digite o nome do aluno: clara
digite a nota do aluno: 8
digite o nome do aluno: pedro
digite a nota do aluno: 5
digite o nome do aluno: joao 
digite a nota do aluno: 7
media das notas :  6.666666666666667


In [138]:
#correcao

alunos = {}
for i in range(1,4):
    nome = input(f"digite o nome do {i} aluno: ")
    nota = float(input(f"digite a nota do {i} aluno: "))
    alunos[nome] = nota

    print()


digite o nome do 1 aluno: clara
digite a nota do 1 aluno: 8

digite o nome do 2 aluno: pedro
digite a nota do 2 aluno: 5

digite o nome do 3 aluno: luisa
digite a nota do 3 aluno: 7



In [139]:
alunos

{'clara': 8.0, 'pedro': 5.0, 'luisa': 7.0}

In [140]:
alunos.values()

dict_values([8.0, 5.0, 7.0])

In [142]:
soma = 0

for nota in alunos.values():
  soma = soma + nota
print("media",soma/len(alunos))


media 6.666666666666667


In [ ]:
# 3. Matriz: Dada a matriz abaixo, construa uma estrutura de repetição para percorrer e somar todos os elementos da matriz

# matriz = np.array([[3, 4, 1],
#                    [3, 1, 5]])

In [143]:
import numpy as np

matriz = np.array([[3,4,1],
                    [3,1,5]])

soma = 0

for linha in matriz :
  for elemento in linha :
    soma = soma + elemento

print("soma dos elementos",soma)

soma dos elementos 17
